print ("Hotel bill Calculator")
people= int(input("How many people stayed in the room for the two nights?:"))
money = int(input("How much is the fee per night?:"))
tip = int(input("How many percent are we going to tip?:"))
fee= (money * 2)
percent= ((tip / 100) * fee)
sum = (fee + percent)
answer = (sum // people)
print ("Everyone has to bring", answer,"each")